### ISSUE TITLE
Solution issue

### ISSUE THREAD

**Issue by alexbriannaughton** [brewchetta/phase-3-ar-practice-karaoke-mania#1]
It seems the solution for KaraokeSinger.songs_by_artist isn't what the directions are asking for. The directions say "returns an array of songs by a specified artist that karaoke_singer has sung" and the solution yields the name of all artists that karaoke_singer has sung.

I did:

self.songs.where("artist_name = ?", artist)

Thanks : )

**Comment by brewchetta** [comment]
Incorporated your solution into the code, thanks for paying attention there!
